### ISSUE TITLE
The service denied use of the directions service by this application

### ISSUE THREAD

**Issue by duraiganesh0** [poulpix/PXGoogleDirections#13]
I Am getting htis error. The service denied use of the directions service by this application

**Comment by poulpix** [comment]
HI @duraiganesh0, did you make sure you got an appropriate Google Maps Directions API key?
To check this, go to this URL: https://console.developers.google.com/apis/credentials, then ensure your Google project is selected in the upper right dropdown box, and finally make sure Google has delivered a "Server" API key for your needs.
Also, it goes without saying, but you also need to make sure there isn't any problem when copy/pasting the key into your source code.
If you still have troubles, don't hesitate to reply and please give me further details.
Thanks for using this library!

**Comment by duraiganesh0** [comment]
@poulpix thanks for your reply. yes it was the problem. now its working well
