### ISSUE TITLE
Add this module to single project

### ISSUE THREAD

**Issue by iThanh** [poulpix/PXGoogleDirections#19]
Dear Sir,

Thank you for your module. So cool!
But I can't use it in my project.
I try to add flowing code to my project, but i can't try to work with!
Please help me, how to use it.
Have some documents, please!
Thank you!

`directionsAPI.delegate = self
        directionsAPI.from     = PXLocation.CoordinateLocation(from)
        directionsAPI.to       = PXLocation.CoordinateLocation(to)
directionsAPI.calculateDirections { (response) -> Void in
            dispatch_async(dispatch_get_main_queue(), { () -> Void in
                switch response {
                case let .Error(_, error): break
                case let .Success(request, routes): break
                }
            })
        }`

**Comment by poulpix** [comment]
Hi, @iThanh 
Please tell me what errors you are seeing with this code?

**Comment by poulpix** [comment]
Hi @iThanh, do you still have issues with this framework?
Otherwise I will have to close the ticket.
Thanks!
