### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [poulpix/PXGoogleDirections#20]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by poulpix** [comment]
Yes, I'm in the process of migrating to Swift 3 and also making it compatible with Google's new Maps frameworks.
I should be able to post a new v1.3 soon.

**Comment by poulpix** [comment]
Finished in V1.3

**Comment by lfarah** [comment]
Thanks @poulpix, you're awesome!
