### ISSUE TITLE
Pod file issue

### ISSUE THREAD

**Issue by sarathnk** [poulpix/PXGoogleDirections#22]
[!] The 'Pods-OzoneRides' target has frameworks with conflicting names: googlemapsbase.framework, googlemaps.framework, and googlemapscore.framework.

**Comment by poulpix** [comment]
Hi @sarathnk, I would be glad to help, since messing with Google Maps frameworks in Cocoapods can be really daunting, but could you please give me more info about your use case?
To begin with, a copy of your Podfile?
Thanks

**Comment by sarathnk** [comment]
@poulpix thanks.Solved issue
.Great work .

**Comment by ahikmatf** [comment]
may i know how you resolve this issue? kinda having the same problem

**Comment by sarathnk** [comment]
Manuallly adding google map framework.
