### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by ranleung** [poulpix/PXGoogleDirections#23]
Hi, 
I am having trouble build this on swift 3.  I am getting the errors:

<img width="373" alt="screen shot 2016-11-25 at 4 42 59 pm" src="https://cloud.githubusercontent.com/assets/5177175/20637017/5819ada8-b32e-11e6-9858-091cf2efdefa.png">

as if its not converted yet.  Anyone else having trouble with this?  Thanks!

**Comment by ranleung** [comment]
my Podfile line:

`pod 'PXGoogleDirections'`

**Comment by sashamelcher** [comment]
'pod update' should help.

**Comment by poulpix** [comment]
Hi @ranleung 
Indeed, it looks like you're not compiling with the newest, V1.3 Pod release.
Could you try a `pod update` in your project, as @sash83 suggested?
Thanks

**Comment by ranleung** [comment]
Thanks! Worked 👍
