### ISSUE TITLE
Unable to use this with Google-Maps-iOS-Utils

### ISSUE THREAD

**Issue by jhhomme** [poulpix/PXGoogleDirections#24]
hi there, i seems to be having problem integrating PXGoogleDirections into my current project where Google-Maps-iOS-Utils is already installed

is there a workaround to this problem?

**Comment by poulpix** [comment]
Hi @jhhomme, what do you mean by "having problem"? What are the error messages you're getting?

**Comment by poulpix** [comment]
Hey @jhhomme, any update on this issue? Could you please give me more info  regarding the problem you're having? Thanks!
