### ISSUE TITLE
i can't run this PXGoogleDirections, do you think api_key need?

### ISSUE THREAD

**Issue by mhtranbn** [poulpix/PXGoogleDirections#26]
i dont known i change to : 
`var preparedRequest = "\(PXGoogleDirections.apiBaseURL)?origin=\(f)&destination=\(t)"`
it can run, but first i can't run :
			`var preparedRequest = "\(PXGoogleDirections.apiBaseURL)?key=\(PXGoogleDirections.apiKey)&origin=\(f)&destination=\(t)"`
https://yadi.sk/i/xYNUR7dW37kkLv
 many thank for supports!

**Comment by poulpix** [comment]
Hi @mhtranbn, yes I think you need to create a Google Maps API key for your iOS app and set it in the code.
Also, check the Debug messages, usually the Google Maps SDK will write error or warning messages to the Debug console to help you troubleshoot issues.
Let me know if you still have troubles after doing that.

**Comment by poulpix** [comment]
Hey @mhtranbn, any update on this one ?
