### ISSUE TITLE
Many compiler errors in a Swift 3 project

### ISSUE THREAD

**Issue by vinceyuan** [poulpix/PXGoogleDirections#27]
Xcode Version 8.2.1 (8C1002)
<img width="362" alt="screen shot 2017-01-16 at 1 20 35 am" src="https://cloud.githubusercontent.com/assets/1109524/21964605/2227f3e2-db8a-11e6-964d-c1ebc604d1c0.png">

**Comment by poulpix** [comment]
Hi @vinceyuan, this is strange, are you sure you are using the Pod's latest version (1.3)?
Only this version has been rewritten in Swift 3.

**Comment by vinceyuan** [comment]
@poulpix You are right. I was using the old version. `pod repo update` solved the problem.

**Comment by poulpix** [comment]
Glad you sorted this out!
