### ISSUE TITLE
http://stackoverflow.com/questions/42725437/the-service-denied-use-of-the-directions-service-by-this-application

### ISSUE THREAD

**Issue by smemamian** [poulpix/PXGoogleDirections#29]
hi
please answer this question:
http://stackoverflow.com/questions/42725437/the-service-denied-use-of-the-directions-service-by-this-application

I downloaded your example project but I got this errors:
<img width="992" alt="screen shot 2017-03-10 at 22 18 04" src="https://cloud.githubusercontent.com/assets/2825656/23808580/9c80e304-05df-11e7-84ac-4bcbda7627a8.png">

------

<img width="279" alt="screen shot 2017-03-10 at 22 18 18" src="https://cloud.githubusercontent.com/assets/2825656/23808620/bebd83e6-05df-11e7-8a45-fb9181efeab8.png">

**Comment by smemamian** [comment]
I solved three errors, but now I got others errors:

<img width="849" alt="hhhh" src="https://cloud.githubusercontent.com/assets/2825656/23808838/8df49ce4-05e0-11e7-85c5-d37f52ca4c6e.png">

**Comment by smemamian** [comment]
now, I have one error in sample project:

```
<unknown>:0: error: no such file or directory: '/Users/sm_emamian/Desktop/PXGoogleDirections/Sample/Private/GoogleAPIKeyProvider.swift'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

**Comment by poulpix** [comment]
Hi @smemamian,
This is the intended behavior. My personal Google API key has been removed from the sample code and from the Git repo.
If you look at the AppDelegate.swift file, you will see a // TODO line with instructions on how to put your own Google API key to get the sample working.
Cheers
