### ISSUE TITLE
draws 2 routes or wrong route calculation

### ISSUE THREAD

**Issue by ghost** [poulpix/PXGoogleDirections#30]
In a few cases two routes are drawn. Is there any way to just show one of them, even though distance of both may be the same?
<img width="352" alt="screen shot 2017-03-11 at 16 58 31" src="https://cloud.githubusercontent.com/assets/16719918/23824761/bc02530a-067c-11e7-8183-f04060a20559.png">

This is also weird. Any ideas what wrong drawing causes?
<img width="350" alt="screen shot 2017-03-11 at 18 43 39" src="https://cloud.githubusercontent.com/assets/16719918/23825489/eacdfa8c-068a-11e7-985a-9db6c7939302.png">

**Comment by smemamian** [comment]
please post your codes because I have some problems by sample codes.

**Comment by ghost** [comment]
I use sample code:

`for i in 0 ..< results.count {
			if i != routeIndex {
				results[i].drawOnMap(mapView, approximate: false, strokeColor: UIColor.lightGray, strokeWidth: 3.0)
			}
		}`


I basically just want to draw one route (the fastest).

**Comment by poulpix** [comment]
Hi @localsDeveloper, the first route in the `results` var should be the best of all the results.
Your code is indeed drawing all the routes but if you only pick the first you should be all set.
Please tell me if this helps or not.

**Comment by ghost** [comment]
Yes, it seems to work! Just picking the first route.

**Comment by poulpix** [comment]
Glad it helped! Closing this thread now.
