### ISSUE TITLE
Add New Example

### ISSUE THREAD

**Issue by embassem** [poulpix/PXGoogleDirections#31]
Add  new Example that use Pods  to add Goole SDK  with 'PXGoogleDirections

# Pods for PodExample
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'PXGoogleDirections'

we still get Error from cocopods  after add  -framework to Other Linker Flags
"[!] The 'Pods-App' target has frameworks with conflicting names: googlemapsbase.framework, googlemaps.framework, and googlemapscore.framework."

**Comment by poulpix** [comment]
Linked to #33 and #28

**Comment by poulpix** [comment]
The Readme has been updated with a specific paragraph regarding this: "Compatibility with Google pods"
