### ISSUE TITLE
Pod install error googlemaps.framworks

### ISSUE THREAD

**Issue by ahmedAlmasri** [poulpix/PXGoogleDirections#33]
i'm using 

pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'PXGoogleDirections'

error  target has frameworks with conflicting names: googlemaps.framework.

**Comment by poulpix** [comment]
Same as #28 
Problem will be fixed within that issue.

Meanwhile, you either need to use `PXGoogleDirections` without Cocoapods, or use both Google SDKs without Cocoapods, but not all together.
