### ISSUE TITLE
calculateDirections() return only one PXGoogleDirectionsRoute always.

### ISSUE THREAD

**Issue by hayaoMobile** [poulpix/PXGoogleDirections#34]
directionAPI.from = PXLocation.coordinateLocation(location1)
directionAPI.to = PXLocation.coordinateLocation(location2)

directionAPI.calculateDirections({ response in
    switch response {
    case let .error(_, error):
        break
    case let .success(_, routes):
        print(routes.count)
        break
    }
})

Then always return only one value.
Please help me.

**Comment by poulpix** [comment]
Hi @hayaoMobile, could you please give me one or more examples of source and destination coordinates that trigger this issue?
Thanks

**Comment by poulpix** [comment]
Closing the issue (no details provided)
