### ISSUE TITLE
Precision route

### ISSUE THREAD

**Issue by simofu88** [poulpix/PXGoogleDirections#4]
Hi...I have a problem with drawing route.

The route is not accurate (see image in attachment).

Have you any solution?

![schermata 2016-01-08 alle 17 15 21](https://cloud.githubusercontent.com/assets/16370334/12202887/61ce3fee-b62c-11e5-832c-b622173e00c4.png)

**Comment by poulpix** [comment]
Hi @simofu88, I'm looking at this.
Could you please give me a sample origin and destination for your search? I've tried with a sample itinerary from via Raffaele Lanciani,Chieti, to via dei Vestini, Chieti, and I have correct route drawings. Thanks!

**Comment by arthurhammer** [comment]
Late answer but the problem might be that you are using the `overviewPolyline` or `path` property of the `PXGoogleDirectionsRoute`. These are just approximations and can get quite off for long routes. Instead, you need to build the path from the legs and steps.

**Comment by poulpix** [comment]
Hey @arthurhammer, @simofu88, thanks for the feedback.
Indeed the drawing functions were using the `overviewPolyline` from the whole route.
In V1.3, there will be a new `detailedPath` property which uses `path` from the legs and steps.

Thanks again.
