### ISSUE TITLE
does it support navigation？

### ISSUE THREAD

**Issue by MarcHe124** [poulpix/PXGoogleDirections#44]

**Comment by poulpix** [comment]
Hi, what do you mean by "supporting navigation"? If you mean tracking the user's location and updating the route steps accordingly, then no, the framework does not support this. At this time PXGoogleDirections is mostly a Swift wrapper around Google's Directions API really. So no CoreLocation features, etc. But you can implement it atop the framework if you like, the framework should already have everything needed in place!
