### ISSUE TITLE
Overall distance and duration of a route object

### ISSUE THREAD

**Issue by poulpix** [poulpix/PXGoogleDirections#7]
Following Sascha's email, it would be nice to have properties giving the overall distance and duration of a PXGoogleDirectionsRoute object. It might not be possible to return PXGoogleDirectionsDuration and PXGoogleDirectionsDistance objects directly, but at least raw NSTimeInterval and CLLocationDistance objects should be feasible.

**Comment by sashamelcher** [comment]
With this extension in the PXGoogleDirectionsRoute file, you can get the total duration of a route with one leg:

`extension PXGoogleDirectionsRoute {
    public var totalDuration: NSTimeInterval {
        get {
            var td = 0 as NSTimeInterval
            for l in legs {
                guard let ld = l.duration, d = ld.duration else {
                    break
                }
                td += d
            }
            return td
        }
    }
}`

In my case it gives me the duration for my routes (as I only have routes with one leg) in seconds which I then convert into minutes.

`let ti = NSInteger(totalDuration)
let minutes = (ti / 60) % 60`

It works!

Thanks Romain!

**Comment by poulpix** [comment]
Since V1.2.3, the `PXGoogleDirectionsRoute` class now has two new properties:

``` swift
var totalDuration: NSTimeInterval
```

returns the total duration of a route, in seconds, and:

``` swift
var totalDistance: CLLocationDistance
```

returns the total distance of a route, in meters.

**Comment by sashamelcher** [comment]
Hi!

Will you update your PXGoogleDirections library to Swift 3?
I am nearly finished with my project and I would love to use your work in
there.

Best regards,

Sascha

2016-03-06 12:52 GMT+01:00 Romain L notifications@github.com:

**Comment by poulpix** [comment]
Hi Sascha,

Yes, I'm in the process of migrating code to Swift 3 and latest Google Maps Pod. 
It should be ready in a few days, with Pod version 1.3. 
Stay tuned and thanks for your support!

Kind regards,

## 

Romain
