### ISSUE TITLE
(response) -> Void in 

### ISSUE THREAD

**Issue by filangelos** [poulpix/PXGoogleDirections#8]
I have completed the pod installation, the API object creation and I cannot run the Directions request. You can find attached a screenshot with the error. Thank you in advance!
<img width="1020" alt="screen shot 2016-02-22 at 11 32 33 pm" src="https://cloud.githubusercontent.com/assets/12871137/13236548/03d4211a-d9bd-11e5-9e05-aae140232920.png">

**Comment by poulpix** [comment]
I've updated the docs, which were not referencing the latest Swift syntax. Check the Readme again and update your code appropriately, it should work now.
Closed with #3 issue.
